---
title: "R Notebook"
output: html_notebook
---

Let's import the iris dataset and explore it

```{r}
data(iris)
```

```{r}
head(iris)
dim(iris)
```
We notice that the iris data has 5 columns and 150 observations/rows

```{r}
colnames(iris)
```

```{r}
summary(iris)
```

```{r}
min(iris$Sepal.Length)
quantile(iris$Sepal.Length,probs=0.25)
median(iris$Sepal.Length)
mean(iris$Sepal.Length)
quantile(iris$Sepal.Length,probs=0.75)
max(iris$Sepal.Length)
```
```{r}
names(sort(-table(iris$Sepal.Length)))[1]
```


```{r}
hist(iris$Sepal.Length)
```

```{r}
hist(iris$Sepal.Width)
```

```{r}
hist(iris$Petal.Length)
```

```{r}
hist(iris$Petal.Width)
```

```{r}
boxplot(iris)
```

```{r}
boxplot.stats(iris$Sepal.Width)
```

```{r}
plot(iris$Species,iris$Sepal.Length)
```

```{r}
plot(iris$Species,iris$Sepal.Width)
```

```{r}
plot(iris$Species,iris$Petal.Length)
```

```{r}
plot(iris$Species,iris$Petal.Width)
```

```{r}
plot(iris$Sepal.Length,iris$Petal.Length)
```

```{r}
plot(iris$Sepal.Width,iris$Petal.Width)
```

```{r}
setosa<-subset(iris,iris$Species=='setosa')
```

```{r}
plot(setosa$Sepal.Length,setosa$Petal.Length)
```

```{r}
plot(setosa$Sepal.Width,setosa$Petal.Width)
```

```{r}
cor(setosa[1:4])
```

```{r}

```

